dist: focal
addons:
  chrome: stable
  apt:
    packages:
    - libnss3-tools
services:
  - xvfb
language: node_js
node_js: 'stable'
before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 3
script: MKCERT=./mkcert make run
