dist: focal
addons:
  # firefox: latest
  chrome: stable
language: node_js
node_js: 'stable'
before_script:
  - npx testcafe --list-browsers
  # - sudo apt-get -y install libnss3-tools
  # - which firefox
script: MKCERT=./mkcert make run
