os:
  - linux
  - osx
dist: focal
addons:
  apt:
    packages:
    - libnss3-tools
  chrome: stable
services:
  - xvfb
language: node_js
node_js: 'stable'
before_script:
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      mkdir -p $HOME/.pki/nssdb
      certutil -d sql:$HOME/.pki/nssdb -N --empty-password
      fluxbox >/dev/null 2>&1 &
      sleep 3
    fi
script: make run
env:
  global:
  - secure: XJ8lOS/i1h2q4psNv02vW59eMDhFqrDGzi9R/xJki+y4cf5NUYM7bJWbCF8dg1UziJPYb0NyhdbcTosodoEO1ooHYmEI1FldlxCEMQy9QxWpg+EsDSmiCnWoV1QFO1uol0hrrKEJzQ52lbHEd4x8bEA80X6e8Tkjc5AdQ2qVfVHizz1en4c9l8h8WRaFqc2JJPvz+DXXAr6STzwpCNYye4l/wJTXF5n6hAD0xeiCKkgdlHpGCfiHqeKhj00mzJ4D+2VUxE2k340O0Fi2h1jNxWQFYEh1u0OkQqKdXjDupEe4uNpp7FA6ek46SD/q5y5aMMLyoL4PLBBTMAxggeiBC0YmWgzxKI4kdvylYG1+RL9ZxNgJTTBljmVh8N6F0qgY0MpthVpyuMJfCnHRTR1mdhfr1wswJ1nLaikGyPiVhwFTgGphUV2ca5gGa+Ej6mkyNnixkdE0ppARF0fsZJWHnSyXhck6YdosAYpSerMXu0N5pWf0K6ZxjbiskCb7xkVPgz1Ml1FHhO8LzrSLFuKEbztjzM2G9jA3xLvNJUKyDIJeD2DJsFtqYJIqYKSZJQ50YHBQLjn8bUcf/yDY8UvTceEnoIx2GIZgZ2rD+Oo9FJnPMYXLIdSYltZbuepe4nq9CXXq2Gkva3Jzd6pVi0nAKFiY9rulL6kOKyxTGDQdabs=
  - secure: axOuUeskQ79/9RNEZUSHC7BTCqYTGiZWWRbJtzWEiTnAkT3RhLM7DKsIf1PMYRA5BXyINKFo5p8lfIpsyli345c/lAEindovz8ZXWEaDcfF96SCzljPWvyvC4cK5p8OafYJ1GadBKdW9YjtY6s8OHCsL8TuX2LThd+4RU5Q83NX9mA05tTrPvC+2Av37J1NLtPOllcEKOodvCR/BVs3FewYqcnGZ7OqNHbIQJmGYHGNgSSATGqML36a9LytBdgNED5uzuCOZWFBZJ75AwVy2k63q/QFPH5mzjNOYmycRZ+mt39Do9DOVTlMo0/46Yz8gIeLTux7qgC2EiO5lFy5eh3zA+UcefZ/G2sZm/DpcNYJfrwszU0M7GUDXNJm5ABxh07/euaW5snbA7Csb0LqAsizbJ813vlS3U0wVvSGM3DR91m+xi7XD33X74PCy+CUt8IgChZAnRtiJfVmZZQpNGTbB+okX0iiWmqFXp1HR+LGX+jNLeuRlHcLf9Kd54hI+XND6uRkwKph2NYr5D8O76izox6PPwfzIAlpndtqmg/NefrtWGN4xz2IIHIr64PML327J4aZI1csULinoS7ODBd3wb3AcPIo/gq9jMUqLMcuhdwXWSqtI1zwckSbPk3MYTIW4q79Guq3EgrERHG909Uls94c1aKuROIpIuNQxFzc=
