dist: focal
addons:
  firefox: latest
  chrome: stable
services:
  - xvfb
language: node_js
node_js: 'stable'
before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 3
  - sudo apt-get -y install libnss3-tools
  - which firefox
script: MKCERT=./mkcert make run
