#! /usr/bin/env bash

# for running macos tests to avoid security constraints on a CI server

if [ "$BROWSER" = "chrome" ]; then
  APP='google chrome'
else
  APP="$BROWSER"
fi

npx testcafe \
    --hostname "$HOSTNAME" \
    --ports "${PORT1},${PORT2}" \
    --selector-timeout "$TIMEOUT" \
    --retry-test-pages \
    --skip-js-errors \
    remote \
    "$TESTS" &

pid=$!
sleep 10
open -a "$APP" "http://${HOSTNAME}:${PORT1}/browser/connect"
wait $pid
