name: end-to-end tests
on: [push]
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome */index.js"
        env:
          HOST: https://client.staging.perio.do
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
