name: end-to-end tests
on: [push, workflow_dispatch]
jobs:
  run-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [ 'chrome', 'firefox' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: DevExpress/testcafe-action@latest
        with:
          args: >-
            ${{ matrix.browser }}
            */index.js
        env:
          HOST: https://client.staging.perio.do
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
