name: end-to-end tests
on: [ push, workflow_dispatch ]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        browser: [ firefox ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx testcafe ${{ matrix.browser }} */index.js  --hostname localhost --retry-test-pages --skip-js-errors --selector-timeout 60000
        env:
          CI: true
          HOST: https://client.staging.perio.do
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
