name: end-to-end tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
        run: make run
