name: end-to-end tests
on: [ push, workflow_dispatch ]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        browser: [ chrome, firefox ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: DevExpress/testcafe-action@latest
        with:
          args: >-
            ${{ matrix.browser }}
            */index.js
            --hostname localhost
            --retry-test-pages
            --skip-js-errors
            --selector-timeout 60000
        env:
          CI: true
          HOST: https://client.staging.perio.do
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
