name: end-to-end tests
on: [ push, workflow_dispatch ]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.flaky }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        browser: [ chrome, firefox ]
        flaky: [ true ]
        exclude:
          - os: ubuntu-latest
            browser: chrome
            flaky: true
        include:
          - os: ubuntu-latest
            browser: chrome
            flaky: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: DevExpress/testcafe-action@latest
        with:
          args: >-
            ${{ matrix.browser }}
            */index.js
            --hostname localhost
            --retry-test-pages
            --skip-js-errors
            --selector-timeout 30000
        env:
          CI: true
          HOST: https://client.staging.perio.do
          ORCID_USER: ${{ secrets.ORCID_USER }}
          ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
